import mongoose, { Schema } from "mongoose";

const UserSchema = new Schema(
  {
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: false },
    googleId: { type: String, unique: true, sparse: true },
    isVerified: { type: Boolean, default: false },
    verificationToken: { type: String },
    resetPasswordToken: { type: String },
    resetPasswordExpires: { type: Date },
    skills: [{ type: String }],
    bio: { type: String },
    avatar: { type: String },
    title: { type: String },
    avatar3d: {
      model: { type: String },
      color: { type: String },
      rotation: { type: Number },
    },
    avatarMode: { type: String, enum: ["2d", "3d"], default: "2d" },
    settings: {
      emailNotifications: { type: Boolean, default: true },
      pushNotifications: { type: Boolean, default: true },
      profilePrivacy: { type: String, enum: ["public", "private"], default: "public" },
      theme: { type: String, default: "dark" },
    },
    lastActive: { type: Date, default: Date.now },
    links: {
      github: { type: String, default: "" },
      linkedin: { type: String, default: "" },
      leetcode: { type: String, default: "" },
      codechef: { type: String, default: "" },
      codeforces: { type: String, default: "" },
      website: { type: String, default: "" },
      portfolio: { type: String, default: "" },
    },
    skillswapId: { type: String, unique: true, sparse: true },
    country: { type: String, default: "India" },
    education: [{
      school: { type: String },
      degree: { type: String },
      gradeType: { type: String, enum: ["GPA", "Percentage", "CGPA"], default: "CGPA" },
      grade: { type: String },
      fromMonth: { type: String },
      fromYear: { type: String },
      toMonth: { type: String },
      toYear: { type: String },
    }],
    experience: [{
      title: { type: String },
      company: { type: String },
      description: { type: String },
      fromMonth: { type: String },
      fromYear: { type: String },
      toMonth: { type: String },
      toYear: { type: String },
      current: { type: Boolean, default: false },
    }],
    achievements: [{
      title: { type: String },
      description: { type: String },
      url: { type: String },
      issueMonth: { type: String },
      issueYear: { type: String },
    }],
    platforms: {
      github: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      leetcode: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      codeforces: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      codechef: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      geeksforgeeks: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      hackerrank: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      interviewbit: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      codestudio: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
      atcoder: { username: { type: String, default: "" }, verified: { type: Boolean, default: false } },
    },
    followers: [{ type: Schema.Types.ObjectId, ref: "User" }],
    following: [{ type: Schema.Types.ObjectId, ref: "User" }],
    rating: { type: Number, default: 0 },
    numReviews: { type: Number, default: 0 },
    totalRatingPoints: { type: Number, default: 0 },
    completedSwaps: { type: Number, default: 0 },
    totalEndorsements: { type: Number, default: 0 },
    totalHours: { type: Number, default: 0 },
    topSkills: [{ 
      name: { type: String },
      count: { type: Number, default: 0 }
    }],
    unlockedBadges: [{ type: String }], // Array of Badge IDs
    isBlocked: { type: Boolean, default: false },
  },
  { timestamps: true },
);

export default mongoose.model("User", UserSchema);
